version: "3.8"

services:
  app:
    image: golang:alpine
    command: sh -c "go build -o app && ./app"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bs23
      POSTGRES_DB: rolebasedcontrol
      CURRENT_SITE: postgres:8081/api/v1/
      BASE_URL: user/email-verify/
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./Role_based_access_control.sql:/docker-entrypoint-initdb.d/Role_based_access_control.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bs23
      POSTGRES_DB: rolebasedcontrol

volumes:
  postgres-data: